### ISSUE TITLE
License

### ISSUE THREAD

**Issue by marys1234** [knackebrot/jellyfin-plugin-enigma2#1]
Can we assign a license to this plug-in?
In that case, there is a chance to add this plug-in to official Jellyfin plug-in repo, see:
https://forum.jellyfin.org/t/vuplus-enigma2-plugin-not-getting-installed/1085/3

Thank You and Best Regards

**Comment by knackebrot** [comment]
Hello and sorry for the late reply.
Yes, after discussing it on #jellyfin Matrix channel I contacted the current maintainer about that in September, and never received a response.
![emby forums](https://user-images.githubusercontent.com/24361046/76034008-f7027a80-5f3d-11ea-8862-6f8e60c45ffb.png)

I can't do much until he adds a license to his repo (https://github.com/MediaBrowser/MediaBrowser.Plugins.VuPlus). If I added one myself here on my own, it would have no weight. If not him, then @CompoUK, he's the original developer (https://github.com/CompoUK/MediaBrowser.Plugins.VuPlus)

**Comment by RAFALFRY** [comment]
Hi
I managed to compile but it doesn't link to vu +
Does it work for you?
`
[2020-09-14 09:46:09.100 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2020-09-14 09:46:09.124 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "MediaBrowser.Plugins.VuPlus, Version=3.1.8.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/MediaBrowser.Plugins.VuPlus/MediaBrowser.Plugins.VuPlus.dll"
[2020-09-14 09:46:13.875 +00:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "MediaBrowser.Plugins.VuPlus.LiveTvService"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'MediaBrowser.Plugins.VuPlus.LiveTvService'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)`

![image](https://user-images.githubusercontent.com/71260335/93073208-d6e90c00-f682-11ea-954a-812b78f46dd6.png)



Everything works up to version 10.5.5.
As of v10.6 it does not connect.

**Comment by knackebrot** [comment]
@RAFALFRY Hi,
Logger is injected differently in .NET Standard 2.1. I've updated the branch, it should work now.

**Comment by RAFALFRY** [comment]
It works.
Thank you.

**Comment by nekocentral** [comment]
To be fair, i don't think they are going to add the license to the upstream repo so even if you think it might not hold weight it might be better to add it as the plugin developer hasn't shown any activity in 4-5 years.

**Comment by next2non** [comment]
Hi

I'm interested in installing this plugin to my Jellyfin but don't know how to add it manually. Is it possible to guide me?

Thanks in advance

Regards

**Comment by knackebrot** [comment]
@nekocentral 
I've added a CC0 (public domain) license.

@next2non 
You should now be able to grab MediaBrowser.Plugins.VuPlus.dll from [Releases](https://github.com/knackebrot/jellyfin-plugin-vuplus/releases). You only need to drop it to your plugins directory and restart Jellyfin. The location of the directory varies by platform and install method: https://jellyfin.org/docs/general/server/plugins/index.html

**Comment by next2non** [comment]
Thanks for the guide. One more help, after I added the dll file and restarted Jellyfin, I get the VuPlus Recording folder appearing, but don’t see my TV channels anywhere? I did put the IP address for my Vu+ in the setting. Am I doing something wrong? Sorry for the inconvenience.

Regards

**Comment by knackebrot** [comment]
@next2non
In Admin Dashboard click Scheduled Tasks and try running TaskRefreshChannels or Refresh Guide. It's set to run every 24 hours, but probably didn't run automatically when you updated your settings.

**Comment by next2non** [comment]
Thank you very much, that did the job
