### ISSUE TITLE
Plugin is not working with Jellyfin 10.0.9.0 :(

### ISSUE THREAD

**Issue by silasmariusz** [knackebrot/jellyfin-plugin-enigma2#24]
Hi

Plugin is not working with Jellyfin 10.0.9.0 :(

Could you please fix that?

Thank you

**Comment by Turtletrumpet** [comment]
Hello, please fix your great plugin for jellyfin 10.9. Thank you!

**Comment by marys1234** [comment]
+1

**Comment by knackebrot** [comment]
Thank you for notifying me. I'll look into this during the upcoming days.

**Comment by Turtletrumpet** [comment]
> Thank you for notifying me. I'll look into this during the upcoming days.

I'm very happy to hear that!

**Comment by Skarabek** [comment]
Hello
On Qnap Jellyfin 10.9.0 the plugin also has the NotSupported status.
Thanks for your work.

**Comment by dzinks** [comment]
I am also waiting for the update and thank you very much for your work and support

**Comment by dominiaz** [comment]
Your plugin is great !!! Waiting for an update :)

**Comment by ghost** [comment]
Love the Plugin! Also would love to see in working on 10.9.0. 👍

**Comment by BeNQ062** [comment]
I'm also waiting for updates for jellyfin 10.9.6, thank you very much

**Comment by knackebrot** [comment]
Version 6.0.0.0 is now available, compatible with Jellyfin 10.9. You can download it from the catalog in your jellyfin admin panel by adding this repository: https://raw.githubusercontent.com/knackebrot/jellyfin-repo/master/manifest.json or from [Releases](https://github.com/knackebrot/jellyfin-plugin-enigma2/releases)

**Comment by Turtletrumpet** [comment]
Thanks a Lot, Mr. Wasa ;-). It works fine.

**Comment by Skarabek** [comment]
Thank you
The plugin works on my Qnap

**Comment by QuatroServis** [comment]
Hello, I am using the plugin on jellyfin 10.11.6 in conjunction with the VU+ receiver from which I pull the stream + EPG. For some channels (HBO3) and similar, the default audio track does not work for me, for me it is CZ audio, it only works in English and I cannot switch anywhere. Is this a bug in the E2 plugin or jelyyfin and can it be fixed?

**Comment by knackebrot** [comment]
@QuatroServis The limitation is Jellyfin itself. It simply selects the first audio track in the stream. About a year ago, I investigated this and found that there are 3 possible technical solutions to this: 
1. Add optional mapping to FFmpeg: Currently, ffmpeg fails if you ask it to map a stream it can't find. If we could feed it something like -map 0:a:language:cze? -map 0:a:language:slo? -map 0:a:0 where it would pick the first language it finds, and fall back to 0:a:0, we could add a list of preferred languages to the plugin.
2. Open the stream, find audio tracks, compare with list from solution 1, select one and feed it to transcoder: For good user experience, this would require us to access the stream through a proxy that would keep the connection open, as opening, analyzing, closing and subsequent opening, analyzing and transcoding would take a few seconds.
3. Proxy between Enigma2 and Jellyfin: Have a remuxing proxy running directly on the Enigma2 box. Make it output e.g. HLS. Filter out the tracks you don't want and reorder the ones you want. This also has the potential to improve user experience, as it would give you a server-side buffer.
