### ISSUE TITLE
Wrong default config for HostName

### ISSUE THREAD

**Issue by sidey79** [knackebrot/jellyfin-plugin-enigma2#7]
I think, the default configuration is wrong and misleading.

https://github.com/knackebrot/jellyfin-plugin-vuplus/blob/4a41cf4b74d02f8c6b253ef97cf7932b74addb6d/MediaBrowser.Plugins.VuPlus/Configuration/PluginConfiguration.cs#L29

It shoud be only the hostname or ip address without any protocol specified here.

**Comment by knackebrot** [comment]
Fixed.
